project1/entrega/wiki/encyclopedia/urls.py
from django.urls import path
from django import forms 
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.title, name="title"),
    path("RandomPage", views.RandomPage, name="RandomPage"),
    path("NewEntryPage", views.NewEntry, name="NewEntryPage"),
    path("wiki/edit/<str:title>", views.EditEntry, name="EditEntry"),
    path("search", views.SearchEntry, name="search_results"),
    
]

project1/entrega/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1/entrega/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

class search(models.Model):
    title=models.CharField(max_length=100,null=True)

project1/entrega/wiki/encyclopedia/views.py
from django.shortcuts import render
import markdown2
from . import util
from django.http import Http404
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
import random
from django import forms
from django.urls import reverse
from django.shortcuts import redirect
from django.db import models
from django.forms import ModelForm 
from .filters import SearchFilter
import re 

class NewentryForm(forms.Form):
    title=forms.CharField(label="Title",widget=forms.TextInput(attrs={'class':'form-control col-lg-5 col-md-5'}))
    contend=forms.CharField(label="Contend",widget=forms.Textarea(attrs={'class': 'form-control col-lg-5 col-md-5'}))

class EditentryForm(forms.Form):
    def __init__(self,title,contend):
        self.title=title
        self.contend=contend
        title=forms.CharField(label="Title",widget=forms.TextInput(attrs={'class':'form-control col-lg-5 col-md-5', 'value':f'{self.title}'}))
        contend=forms.CharField(label="Contend",widget=forms.Textarea(attrs={'class':'form-control col-lg-5 col-md-5','value':f'{self.contend}'}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def title(request,title):
    p=util.list_entries()
    if title not in p:
        return render (request,"encyclopedia/wiki/404.html",{
            "title":title
        })
    else:
        return render(request, "encyclopedia/wiki/entry.html", {
        "contend": markdown2.markdown(util.get_entry(title)),
        "title":title})

def RandomPage(request):
    p=util.list_entries()
    r=random.choice(p)
    return render(request, "encyclopedia/wiki/entry.html", {
    "contend": markdown2.markdown(util.get_entry(r)),
    "title":r})

def SearchEntry(request):
    if request.method == 'POST':
        term = request.POST
        term = term['q']
        #term=term[0]
        entries = util.list_entries()
        searchlist = []
        for entry in entries:
            if re.search(term.lower(), entry.lower()): 
                 searchlist.append(entry)
            
    if term in searchlist:
        return render(request, "encyclopedia/wiki/entry.html", {
            "contend": markdown2.markdown(util.get_entry(term)),
            "title":term})
    else:
        return render(request, "encyclopedia/searchbar.html", {
            'entries': searchlist
        })    

   

def NewEntry(request):
    if request.method == "POST":
        form = NewentryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            contend = form.cleaned_data["contend"]
            p=util.list_entries()
            if title in p:
                return render(request,"encyclopedia/wiki/Newentry.html",{
                    "form":form, "Error":"This Entry Already Exists"})
            util.save_entry(title,contend)
            return HttpResponseRedirect(reverse("title",kwargs={'title':f'{title}'}))
        else:
            return render(request,"encyclopedia/wiki/Newentry.html", {
                "form": form
            })       
    return render(request,"encyclopedia/wiki/Newentry.html",{
        "form":NewentryForm() 
    })

def EditEntry(request,title):
    p=util.list_entries()
    if title in p:
        contend=util.get_entry(title)
        if request.method == "POST":
            form = NewentryForm(request.POST)
            if form.is_valid():
                contend=form.cleaned_data["contend"]
                util.save_entry(title,contend)
                return HttpResponseRedirect(reverse("title",kwargs={'title':f'{title}'}))
                
        return render (request,"encyclopedia/wiki/editpage.html",{
            "title":title,"contend":contend
        })
  
   

project1/entrega/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

project1/entrega/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'search_results' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'NewEntryPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'RandomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/entrega/wiki/encyclopedia/templates/encyclopedia/searchbar.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

project1/entrega/wiki/encyclopedia/templates/encyclopedia/wiki/Newentry.html
{% extends "encyclopedia/wiki/layout.html" %}
{% block title %}
    NewEntry
{% endblock %}

{% block body %}
     <h1>Add New Entry</h1>
     <h3>{{ Error }}</h3>
    <div class="form-group">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-outline-success" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

project1/entrega/wiki/encyclopedia/templates/encyclopedia/wiki/editpage.html
{% extends "encyclopedia/wiki/layout.html" %}
{% block title %}
    EditPage
{% endblock %}

{% block body %}
     <h1>Edit Entry</h1>
        <div class="form-group"></div>   
            <form action="{% url 'EditEntry' title  %}" method="POST">
            {% csrf_token %}
                        <tr><th><label for="id_title">Title:</label></th><td><input type="text" name="title" class="form-control col-lg-5 col-md-5" required id="id_title" value="{{ title }}"></td></tr>
            <tr><th><label for="id_contend">Contend:</label></th><td><textarea name="contend" cols="40" rows="10" class="form-control col-lg-5 col-md-5" required id="id_contend" value="">
                {{ contend|safe }}
            </textarea></td></tr>
                        <button class="btn btn-outline-success" type="submit">Edit</button>
                    </form>
        </div>
      
{% endblock %}

project1/entrega/wiki/encyclopedia/templates/encyclopedia/wiki/entry.html
{% extends "encyclopedia/wiki/layout.html" %}
{% block title %}
    {{title|safe}}
{% endblock %}

{% block body %}
     {{contend|safe}}
    <a class="btn btn-primary" href="edit/{{ title }}" role="button">Edit</a>
{% endblock %}

project1/entrega/wiki/encyclopedia/templates/encyclopedia/wiki/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'search_results' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'NewEntryPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'RandomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/entrega/wiki/encyclopedia/templates/encyclopedia/wiki/random.html
{% extends "encyclopedia/wiki/layout.html" %}
{% block title %}
    {{random|safe}}
{% endblock %}

{% block body %}
     {{contend|safe}}
{% endblock %}